[global]
excludes = ["*.tmpl", "flake.lock", ".git/*", "node_modules/*"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.shell]
command = "shfmt"
options = ["-w", "-i", "4"]
includes = ["*.sh"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.oxfmt]
command = "oxfmt"
options = ["--write"]
includes = ["*.md", "*.json", "*.yaml", "*.yml"]
excludes = ["CLAUDE.md", "**/private_karabiner.json"]
