# mise managed tool versions
# Managed by .github/workflows/update-toolchains.yml
# Add new auto-updated tools in this file.

[tools]
"aqua:FiloSottile/age" = "1.3.1"
apko = "1.2.16"
"github:aria2/aria2" = "release-1.37.0"
bat = "0.26.1"
"bun" = "1.3.14"
"claude-code" = "2.1.174"
codex = "0.139.0"
crane = "0.21.6"
direnv = "2.37.1"
duf = "0.9.1"
dust = "1.2.4"
fastfetch = "2.64.2"
fd = "10.4.2"
gh = "2.94.0"
git-lfs = "3.7.1"
glab = "1.102.0"
gitleaks = "8.30.1"
go = "1.26.4"
gopass = "1.16.1"
hyperfine = "1.20.0"
jq = "1.8.1"
just = "1.52.0"
krew = "0.5.0"
kubectl = "1.36.1"
lazygit = "0.62.2"
melange = "0.53.0"
# nowledge mem
"pipx:nmem-cli" = "0.9.4"
# Oxfmt is a high-performance formatter for the JavaScript ecosystem.
"npm:oxfmt" = "0.54.0"
rg = "15.1.0"
"aqua:joshmedeski/sesh" = "2.26.2"
tlrc = "1.13.1"
tmux = "3.6b"
"aqua:dduan/tre" = "0.4.0"
yazi = "26.5.6"
yq = "4.53.3"
zellij = "0.44.3"
