# mise managed tool versions
# Managed by .github/workflows/update-toolchains.yml
# Add new auto-updated tools in this file.

[tools]
"aqua:FiloSottile/age" = "1.3.1"
apko = "1.2.28"
"github:aria2/aria2" = "release-1.37.0"
bat = "0.26.1"
"bun" = "1.3.14"
"claude-code" = "2.1.220"
"aqua:openai/codex" = "0.145.0"
crane = "0.21.7"
direnv = "2.37.1"
duf = "0.9.1"
dust = "1.2.4"
fastfetch = "2.66.0"
fd = "10.4.2"
gh = "2.96.0"
git-lfs = "3.7.1"
glab = "1.109.0"
gitleaks = "8.30.1"
go = "1.26.5"
gopass = "1.16.1"
hyperfine = "1.20.0"
jq = "1.8.2"
just = "1.57.0"
krew = "0.5.0"
kubectl = "1.36.3"
lazygit = "0.63.1"
melange = "0.56.3"
# nowledge mem
"pipx:nmem-cli" = "0.10.41"
# Oxfmt is a high-performance formatter for the JavaScript ecosystem.
"npm:oxfmt" = "0.60.0"
rg = "15.2.0"
"aqua:joshmedeski/sesh" = "2.27.0"
"aqua:tektoncd/cli" = "0.44.2"
"aqua:tektoncd/pipelines-as-code" = "0.48.1"
tlrc = "1.13.1"
tmux = "3.7b"
"aqua:dduan/tre" = "0.4.0"
yazi = "26.5.6"
yq = "4.53.3"
zellij = "0.44.3"
